name: church_attendance_scanner
description: A Flutter app for church ushers to scan QR codes and mark member attendance
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # QR Code Scanning
  qr_code_scanner: ^1.0.1
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Local Storage & Database
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_secure_storage: ^9.0.0
  
  # UI & Images
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Permissions & Connectivity
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2
  
  # Notifications & Feedback
  flutter_local_notifications: ^16.3.0
  vibration: ^1.8.4
  audioplayers: ^5.2.1
  
  # Utilities
  intl: ^0.19.0
  provider: ^6.1.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # Using system fonts for better compatibility
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
