<?php

namespace Database\Seeders;

use App\Models\Member;
use App\Models\User;
use Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MemberTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $members = [
            [
                'id' => 1,
                'first_name' => 'Derrick',
                'last_name' => 'Doe',
                'email' => 'derrick.doe@gmail.com',
                'phone' => 'Voluptatem est quo r',
                'address' => 'Autem ut voluptatem',
                'date_of_birth' => '2017-12-09',
                'gender' => 'other',
                'marital_status' => 'widowed',
                'occupation' => 'Velit magni dolor lo',
                'emergency_contact_name' => 'Ut accusantium volup',
                'emergency_contact_phone' => 'Accusantium placeat',
                'baptism_date' => '1985-09-10',
                'membership_date' => '2017-12-09',
                'is_active' => true,
                'notes' => 'Rem debitis dolor qu',
                'profile_image_path' => null,
                'user_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 2,
                'first_name' => 'Rachel',
                'last_name' => 'Doe',
                'email' => 'rachel.doe@gmail.com',
                'phone' => 'Voluptatem est quo r',
                'address' => 'Autem ut voluptatem',
                'date_of_birth' => '2017-12-09',
                'gender' => 'other',
                'marital_status' => 'widowed',
                'occupation' => 'Velit magni dolor lo',
                'emergency_contact_name' => 'Ut accusantium volup',
                'emergency_contact_phone' => 'Accusantium placeat',
                'baptism_date' => '1985-09-10',
                'membership_date' => '2017-12-09',
                'is_active' => true,
                'notes' => 'Rem debitis dolor qu',
                'profile_image_path' => null,
                'user_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 3,
                'first_name' => 'Mary',
                'last_name' => 'Pearson',
                'email' => 'mary.pearson@gmail.com',
                'phone' => 'Voluptatem est quo r',
                'address' => 'Autem ut voluptatem',
                'date_of_birth' => '2017-12-09',
                'gender' => 'other',
                'marital_status' => 'widowed',
                'occupation' => 'Velit magni dolor lo',
                'emergency_contact_name' => 'Ut accusantium volup',
                'emergency_contact_phone' => 'Accusantium placeat',
                'baptism_date' => '1985-09-10',
                'membership_date' => '2017-12-09',
                'is_active' => true,
                'notes' => 'Rem debitis dolor qu',
                'profile_image_path' => null,
                'user_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 4,
                'first_name' => 'Eunice',
                'last_name' => 'Victory',
                'email' => 'eunice.victory@gmail.com',
                'phone' => 'Voluptatem est quo r',
                'address' => 'Autem ut voluptatem',
                'date_of_birth' => '2017-12-09',
                'gender' => 'other',
                'marital_status' => 'widowed',
                'occupation' => 'Velit magni dolor lo',
                'emergency_contact_name' => 'Ut accusantium volup',
                'emergency_contact_phone' => 'Accusantium placeat',
                'baptism_date' => '1985-09-10',
                'membership_date' => '2017-12-09',
                'is_active' => true,
                'notes' => 'Rem debitis dolor qu',
                'profile_image_path' => null,
                'user_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 5,
                'first_name' => 'Abraham',
                'last_name' => 'Doe',
                'email' => 'abraham.doe@gmail.com',
                'phone' => 'Voluptatem est quo r',
                'address' => 'Autem ut voluptatem',
                'date_of_birth' => '2017-12-09',
                'gender' => 'other',
                'marital_status' => 'widowed',
                'occupation' => 'Velit magni dolor lo',
                'emergency_contact_name' => 'Ut accusantium volup',
                'emergency_contact_phone' => 'Accusantium placeat',
                'baptism_date' => '1985-09-10',
                'membership_date' => '2017-12-09',
                'is_active' => true,
                'notes' => 'Rem debitis dolor qu',
                'profile_image_path' => null,
                'user_id' => 4,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 6,
                'first_name' => 'John',
                'last_name' => 'Doe',
                'email' => 'john.doe@example.com',
                'phone' => '+233-20-123-4567',
                'address' => '123 Main Street, Accra, Ghana',
                'date_of_birth' => '1985-03-15',
                'gender' => 'male',
                'marital_status' => 'married',
                'occupation' => 'Software Engineer',
                'emergency_contact_name' => 'Jane Doe',
                'emergency_contact_phone' => '+233-20-123-4568',
                'baptism_date' => '1995-06-20',
                'membership_date' => '2010-01-15',
                'is_active' => true,
                'notes' => 'Active member, attends regularly',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 7,
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'email' => 'sarah.johnson@example.com',
                'phone' => '+233-20-234-5678',
                'address' => '456 Oak Avenue, Kumasi, Ghana',
                'date_of_birth' => '1990-07-22',
                'gender' => 'female',
                'marital_status' => 'single',
                'occupation' => 'Teacher',
                'emergency_contact_name' => 'Michael Johnson',
                'emergency_contact_phone' => '+233-20-234-5679',
                'baptism_date' => '2000-08-10',
                'membership_date' => '2012-03-20',
                'is_active' => true,
                'notes' => 'Youth ministry leader',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 8,
                'first_name' => 'Michael',
                'last_name' => 'Jackson',
                'email' => 'michael.jackson@example.com',
                'phone' => '+233-20-345-6789',
                'address' => '789 Pine Road, Tamale, Ghana',
                'date_of_birth' => '1978-11-08',
                'gender' => 'male',
                'marital_status' => 'married',
                'occupation' => 'Business Owner',
                'emergency_contact_name' => 'Grace Osei',
                'emergency_contact_phone' => '+233-20-345-6790',
                'baptism_date' => '1988-12-25',
                'membership_date' => '2005-09-10',
                'is_active' => true,
                'notes' => 'Elder, prayer team member',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 9,
                'first_name' => 'Grace',
                'last_name' => 'Pearson',
                'email' => 'grace.pearson@example.com',
                'phone' => '+233-20-456-7890',
                'address' => '321 Elm Street, Cape Coast, Ghana',
                'date_of_birth' => '1982-04-12',
                'gender' => 'female',
                'marital_status' => 'married',
                'occupation' => 'Nurse',
                'emergency_contact_name' => 'Kwame Mensah',
                'emergency_contact_phone' => '+233-20-456-7891',
                'baptism_date' => '1992-05-15',
                'membership_date' => '2008-07-05',
                'is_active' => true,
                'notes' => 'Children\'s ministry coordinator',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 10,
                'first_name' => 'David',
                'last_name' => 'Jamieson',
                'email' => 'david.jamieson@example.com',
                'phone' => '+233-20-567-8901',
                'address' => '654 Maple Drive, Sunyani, Ghana',
                'date_of_birth' => '1995-09-30',
                'gender' => 'male',
                'marital_status' => 'single',
                'occupation' => 'Student',
                'emergency_contact_name' => 'Elizabeth Kufuor',
                'emergency_contact_phone' => '+233-20-567-8902',
                'baptism_date' => '2005-10-20',
                'membership_date' => '2015-02-14',
                'is_active' => true,
                'notes' => 'Youth group member',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 11,
                'first_name' => 'Patricia',
                'last_name' => 'Addo',
                'email' => 'patricia.kwesi@example.com',
                'phone' => '+233-20-678-9012',
                'address' => '987 Cedar Lane, Ho, Ghana',
                'date_of_birth' => '1988-12-03',
                'gender' => 'female',
                'marital_status' => 'divorced',
                'occupation' => 'Accountant',
                'emergency_contact_name' => 'Robert Addo',
                'emergency_contact_phone' => '+233-20-678-9013',
                'baptism_date' => '1998-01-18',
                'membership_date' => '2011-11-30',
                'is_active' => true,
                'notes' => 'Finance committee member',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 12,
                'first_name' => 'Kwame',
                'last_name' => 'Asante',
                'email' => 'kwame.asante@example.com',
                'phone' => '+233-20-789-0123',
                'address' => '147 Birch Court, Koforidua, Ghana',
                'date_of_birth' => '1975-06-18',
                'gender' => 'male',
                'marital_status' => 'married',
                'occupation' => 'Pastor',
                'emergency_contact_name' => 'Abena Asante',
                'emergency_contact_phone' => '+233-20-789-0124',
                'baptism_date' => '1985-07-22',
                'membership_date' => '2000-04-12',
                'is_active' => true,
                'notes' => 'Senior pastor, leadership team',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 13,
                'first_name' => 'Abena',
                'last_name' => 'Owusu',
                'email' => 'abena.owusu@example.com',
                'phone' => '+233-20-890-1234',
                'address' => '258 Spruce Way, Tema, Ghana',
                'date_of_birth' => '1992-02-14',
                'gender' => 'female',
                'marital_status' => 'single',
                'occupation' => 'Marketing Manager',
                'emergency_contact_name' => 'Kofi Owusu',
                'emergency_contact_phone' => '+233-20-890-1235',
                'baptism_date' => '2002-03-25',
                'membership_date' => '2013-06-08',
                'is_active' => true,
                'notes' => 'Outreach team leader',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 14,
                'first_name' => 'Emmanuel',
                'last_name' => 'Darko',
                'email' => 'emmanuel.darko@example.com',
                'phone' => '+233-20-901-2345',
                'address' => '369 Willow Street, Sekondi, Ghana',
                'date_of_birth' => '1980-08-25',
                'gender' => 'male',
                'marital_status' => 'married',
                'occupation' => 'Engineer',
                'emergency_contact_name' => 'Ruth Darko',
                'emergency_contact_phone' => '+233-20-901-2346',
                'baptism_date' => '1990-09-30',
                'membership_date' => '2006-12-01',
                'is_active' => true,
                'notes' => 'Technical team member',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 15,
                'first_name' => 'Ruth',
                'last_name' => 'Boateng',
                'email' => 'ruth.boateng@example.com',
                'phone' => '+233-20-012-3456',
                'address' => '741 Poplar Avenue, Obuasi, Ghana',
                'date_of_birth' => '1987-01-07',
                'gender' => 'female',
                'marital_status' => 'married',
                'occupation' => 'Doctor',
                'emergency_contact_name' => 'Samuel Boateng',
                'emergency_contact_phone' => '+233-20-012-3457',
                'baptism_date' => '1997-02-12',
                'membership_date' => '2009-08-22',
                'is_active' => true,
                'notes' => 'Health ministry coordinator',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 16,
                'first_name' => 'Samuel',
                'last_name' => 'Sarpong',
                'email' => 'samuel.sarpong@example.com',
                'phone' => '+233-20-123-4567',
                'address' => '852 Cherry Road, Bolgatanga, Ghana',
                'date_of_birth' => '1973-05-20',
                'gender' => 'male',
                'marital_status' => 'widowed',
                'occupation' => 'Retired Teacher',
                'emergency_contact_name' => 'Esther Sarpong',
                'emergency_contact_phone' => '+233-20-123-4568',
                'baptism_date' => '1983-06-15',
                'membership_date' => '1998-10-05',
                'is_active' => true,
                'notes' => 'Senior ministry, prayer warrior',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 17,
                'first_name' => 'Esther',
                'last_name' => 'Mensah',
                'email' => 'esther.mensah@example.com',
                'phone' => '+233-20-234-5678',
                'address' => '963 Ash Street, Wa, Ghana',
                'date_of_birth' => '1993-11-11',
                'gender' => 'female',
                'marital_status' => 'single',
                'occupation' => 'Social Worker',
                'emergency_contact_name' => 'Daniel Mensah',
                'emergency_contact_phone' => '+233-20-234-5679',
                'baptism_date' => '2003-12-20',
                'membership_date' => '2014-04-15',
                'is_active' => true,
                'notes' => 'Community outreach coordinator',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 18,
                'first_name' => 'Daniel',
                'last_name' => 'Agyemang',
                'email' => 'daniel.agyemang@example.com',
                'phone' => '+233-20-345-6789',
                'address' => '159 Oak Street, Navrongo, Ghana',
                'date_of_birth' => '1984-07-04',
                'gender' => 'male',
                'marital_status' => 'married',
                'occupation' => 'Farmer',
                'emergency_contact_name' => 'Hannah Agyemang',
                'emergency_contact_phone' => '+233-20-345-6790',
                'baptism_date' => '1994-08-08',
                'membership_date' => '2007-05-18',
                'is_active' => true,
                'notes' => 'Agriculture ministry leader',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 19,
                'first_name' => 'Hannah',
                'last_name' => 'Osei',
                'email' => 'hannah.osei@example.com',
                'phone' => '+233-20-456-7890',
                'address' => '357 Pine Avenue, Bawku, Ghana',
                'date_of_birth' => '1989-03-28',
                'gender' => 'female',
                'marital_status' => 'married',
                'occupation' => 'Banker',
                'emergency_contact_name' => 'Joseph Osei',
                'emergency_contact_phone' => '+233-20-456-7891',
                'baptism_date' => '1999-04-30',
                'membership_date' => '2010-09-12',
                'is_active' => true,
                'notes' => 'Finance ministry member',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 20,
                'first_name' => 'Joseph',
                'last_name' => 'Kyei',
                'email' => 'joseph.kyei@example.com',
                'phone' => '+233-20-567-8901',
                'address' => '486 Elm Drive, Yendi, Ghana',
                'date_of_birth' => '1976-12-16',
                'gender' => 'male',
                'marital_status' => 'married',
                'occupation' => 'Police Officer',
                'emergency_contact_name' => 'Deborah Kyei',
                'emergency_contact_phone' => '+233-20-567-8902',
                'baptism_date' => '1986-01-25',
                'membership_date' => '2001-07-03',
                'is_active' => true,
                'notes' => 'Security ministry coordinator',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 21,
                'first_name' => 'Deborah',
                'last_name' => 'Addo',
                'email' => 'deborah.addo@example.com',
                'phone' => '+233-20-678-9012',
                'address' => '753 Maple Lane, Damongo, Ghana',
                'date_of_birth' => '1991-06-09',
                'gender' => 'female',
                'marital_status' => 'single',
                'occupation' => 'Teacher',
                'emergency_contact_name' => 'Isaac Addo',
                'emergency_contact_phone' => '+233-20-678-9013',
                'baptism_date' => '2001-07-14',
                'membership_date' => '2012-12-25',
                'is_active' => true,
                'notes' => 'Sunday school teacher',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 22,
                'first_name' => 'Isaac',
                'last_name' => 'Owusu',
                'email' => 'isaac.owusu@example.com',
                'phone' => '+233-20-789-0123',
                'address' => '951 Cedar Street, Salaga, Ghana',
                'date_of_birth' => '1983-09-22',
                'gender' => 'male',
                'marital_status' => 'married',
                'occupation' => 'Businessman',
                'emergency_contact_name' => 'Rebecca Owusu',
                'emergency_contact_phone' => '+233-20-789-0124',
                'baptism_date' => '1993-10-28',
                'membership_date' => '2008-03-17',
                'is_active' => true,
                'notes' => 'Business ministry leader',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 23,
                'first_name' => 'Ann',
                'last_name' => 'Rock',
                'email' => 'ann.rock@example.com',
                'phone' => '+233-20-890-1234',
                'address' => '258 Spruce Way, Tema, Ghana',
                'date_of_birth' => '1992-02-14',
                'gender' => 'female',
                'marital_status' => 'single',
                'occupation' => 'Marketing Manager',
                'emergency_contact_name' => 'Kofi Owusu',
                'emergency_contact_phone' => '+233-20-890-1235',
                'baptism_date' => '2002-03-25',
                'membership_date' => '2013-06-08',
                'is_active' => true,
                'notes' => 'Family Head',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 24,
                'first_name' => 'Enda',
                'last_name' => 'Owusu',
                'email' => 'enda.owusu@example.com',
                'phone' => '+233-20-890-1234',
                'address' => '258 Spruce Way, Tema, Ghana',
                'date_of_birth' => '1992-02-14',
                'gender' => 'female',
                'marital_status' => 'married',
                'occupation' => 'Marketing Manager',
                'emergency_contact_name' => 'Kofi Owusu',
                'emergency_contact_phone' => '+233-20-890-1235',
                'baptism_date' => '2002-03-25',
                'membership_date' => '2013-06-08',
                'is_active' => true,
                'notes' => 'Family Head',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'id' => 25,
                'first_name' => 'Jessica',
                'last_name' => 'Oyeson',
                'email' => 'jessica.oyeso@example.com',
                'phone' => '+233-20-890-1234',
                'address' => '258 Spruce Way, Tema, Ghana',
                'date_of_birth' => '1992-02-14',
                'gender' => 'male',
                'marital_status' => 'married',
                'occupation' => 'Marketing Manager',
                'emergency_contact_name' => 'Kofi Owusu',
                'emergency_contact_phone' => '+233-20-890-1235',
                'baptism_date' => '2002-03-25',
                'membership_date' => '2013-06-08',
                'is_active' => true,
                'notes' => 'Family Head',
                'profile_image_path' => null,
                'user_id' => null,
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];

       //create members and users
       foreach ($members as $member) {
        $user = User::create([
            'id' => $member['id']+3,
            'name' => $member['first_name'] . ' ' . $member['last_name'],
            'email' => $member['email'],
            'phone' => $member['phone'],
            'address' => $member['address'],
            'date_of_birth' => $member['date_of_birth'],
            'gender' => $member['gender'],
            'password' => Hash::make('password'),
            'is_active' => true,
            'email_verified_at' => now(),
        ]);

        //edit array of members with user_id
        $member['user_id'] = $user->id;
        Member::create($member);
       }
    }
}
